spring.application.name=HelloWorld

# Supabase Mumbai
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.uhcbuijwrkvhtmuerxij
spring.datasource.password=keepGoing123452026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - Set to NONE because tables already exist!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# THE SPEED BOOST
spring.main.lazy-initialization=true
spring.data.jpa.repositories.bootstrap-mode=lazy

# Hikari
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000