spring.application.name=HelloWorld

# Supabase Cloud Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&connectTimeout=10
spring.datasource.username=postgres.jqvbhzvbgyubgberqsan
spring.datasource.password=keepGoing123452026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Connection Pool ? tuned for cloud
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.initialization-fail-timeout=10000

# Production flags
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false